# Generated by Django 5.2.3 on 2025-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_order_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default='No address', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='method_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='method_shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_number',
            field=models.CharField(default='0324234', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
